### ISSUE TITLE
cannot use with webpack: TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mikestaub** [mjpearson/passport-slack#37]
As a workaround, I mark this module as external and manually copy it into the build.

Removing this line will solve the issue:

https://github.com/mjpearson/passport-slack/blob/master/lib/passport-slack/index.js#L10

Here is full stack trace:

```
'TypeError: Path must be a string. Received undefined',
  'at assertPath (path.js:28:11)',
  'at Object.dirname (path.js:1349:5)',
  'at Function.pkginfo.find (/opt/app/backend/.webpack/service/webpack:/node_modules/pkginfo/lib/pkginfo.js:89:1)',
  'at Function.pkginfo.read (/opt/app/backend/.webpack/service/webpack:/node_modules/pkginfo/lib/pkginfo.js:115:1)',
  'at module.exports (/opt/app/backend/.webpack/service/webpack:/node_modules/pkginfo/lib/pkginfo.js:66:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/webpack:/node_modules/passport-oauth/node_modules/passport/lib/passport/index.js:440:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/index.js:100534:30)',
  'at __webpack_require__ (/opt/app/backend/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/webpack:/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:4:1)',
  'at __webpack_require__ (/opt/app/backend/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/webpack:/node_modules/passport-oauth/lib/passport-oauth/index.js:4:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/index.js:99763:30)',
  'at __webpack_require__ (/opt/app/backend/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/webpack:/node_modules/passport-slack/lib/passport-slack/strategy.js:5:1)',
  'at __webpack_require__ (/opt/app/backend/.webpack/service/webpack:/webpack/bootstrap:19:1)',
  'at Object.<anonymous> (/opt/app/backend/.webpack/service/webpack:/node_modules/passport-slack/lib/passport-slack/index.js:4:1)',
```

**Comment by mikestaub** [comment]
This package does not look like it is actively maintained, I would be happy to take it over if you wish.

In the meantime I published my own:

https://github.com/mikestaub/passport-slack

**Comment by rvillanueva** [comment]
Are you sure it's a webpack issue? Seems to be working fine on my setup.

With that said it doesn't seem necessary to expose the version number from the module like that, so probably safe to remove.

**Comment by mikestaub** [comment]
I didn't investigate the root cause fully, but when I used webpack externals it works. It's only when I try to bundle the module do I get the error.
